name: Release Deployment
on:
  release:
    types: [published]
jobs:
  build-deploy-maven-central-package:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Set Proper version
        run: mvn versions:set -ntp -DnewVersion=${{ github.event.release.tag_name }}
      - id: install-secret-key
        name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      - name: Publish package
        run: mvn --batch-mode -ntp -Dmaven.test.skip=true deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      - name: Slack Notification
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: "Publication of ${{ github.event.release.tag_name }} to Maven Central completed! :tada:"
